CREATE TABLE dbo.Countries(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL,
	[ISO2] NVARCHAR(2) NOT NULL,
	[ISO3] NVARCHAR(3) NOT NULL
);

ALTER TABLE dbo.Countries
ADD CONSTRAINT UQ_Countries_ISO2 
UNIQUE (ISO2);

ALTER TABLE dbo.Countries
ADD CONSTRAINT UQ_Countries_ISO3 
UNIQUE (ISO3);


CREATE TABLE dbo.Counties(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL,
	CountryId UNIQUEIDENTIFIER NOT NULL
);

ALTER TABLE dbo.Counties
ADD CONSTRAINT FK_Counties_Countries
FOREIGN KEY (CountryId) REFERENCES dbo.Countries(Id);

ALTER TABLE dbo.Counties
ADD CONSTRAINT UQ_Counties_CountryId_Name 
UNIQUE (CountryId, [Name]);

CREATE TABLE dbo.Cities(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	[Name] NVARCHAR(255) NOT NULL,
	CountyId UNIQUEIDENTIFIER NOT NULL
);

ALTER TABLE dbo.Cities
ADD CONSTRAINT FK_Cities_Counties
FOREIGN KEY (CountyId) REFERENCES dbo.Counties(Id);

ALTER TABLE dbo.Cities
ADD CONSTRAINT UQ_Cities_CountyId_Name 
UNIQUE (CountyId, [Name]);