ALTER TABLE dbo.BuildingRiskIndicators
ADD
	CreatedAt DATETIME2(0) NOT NULL
		CONSTRAINT DF_BuildingRiskIndicators_CreatedAt DEFAULT (SYSUTCDATETIME()),
	UpdatedAt DATETIME2(0) NOT NULL
		CONSTRAINT DF_BuildingRiskIndicators_UpdatedAt DEFAULT (SYSUTCDATETIME());

ALTER TABLE dbo.Buildings
ADD
	CreatedAt DATETIME2(0) NOT NULL
		CONSTRAINT DF_Buildings_CreatedAt DEFAULT (SYSUTCDATETIME()),
	UpdatedAt DATETIME2(0) NOT NULL
		CONSTRAINT DF_Buildings_UpdatedAt DEFAULT (SYSUTCDATETIME());

ALTER TABLE dbo.Cities
ADD
	CreatedAt DATETIME2(0) NOT NULL
		CONSTRAINT DF_Cities_CreatedAt DEFAULT (SYSUTCDATETIME()),
	UpdatedAt DATETIME2(0) NOT NULL
		CONSTRAINT DF_Cities_UpdatedAt DEFAULT (SYSUTCDATETIME());

ALTER TABLE dbo.Clients
ADD
	CreatedAt DATETIME2(0) NOT NULL
		CONSTRAINT DF_Clients_CreatedAt DEFAULT (SYSUTCDATETIME()),
	UpdatedAt DATETIME2(0) NOT NULL
		CONSTRAINT DF_Clients_UpdatedAt DEFAULT (SYSUTCDATETIME());

ALTER TABLE dbo.Counties
ADD
	CreatedAt DATETIME2(0) NOT NULL
		CONSTRAINT DF_Counties_CreatedAt DEFAULT (SYSUTCDATETIME()),
	UpdatedAt DATETIME2(0) NOT NULL
		CONSTRAINT DF_Counties_UpdatedAt DEFAULT (SYSUTCDATETIME());

ALTER TABLE dbo.Countries
ADD
	CreatedAt DATETIME2(0) NOT NULL
		CONSTRAINT DF_Countries_CreatedAt DEFAULT (SYSUTCDATETIME()),
	UpdatedAt DATETIME2(0) NOT NULL
		CONSTRAINT DF_Countries_UpdatedAt DEFAULT (SYSUTCDATETIME());

ALTER TABLE dbo.RiskIndicators
ADD
	CreatedAt DATETIME2(0) NOT NULL
		CONSTRAINT DF_RiskIndicators_CreatedAt DEFAULT (SYSUTCDATETIME()),
	UpdatedAt DATETIME2(0) NOT NULL
		CONSTRAINT DF_RiskIndicators_UpdatedAt DEFAULT (SYSUTCDATETIME());